name: starlake
version: '3.8'

services:

  starlake-db:
    image: postgres:17
    restart: on-failure
    container_name: starlake-db
    ports:
      - ${SL_DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${SL_POSTGRES_USER:-dbuser}
      POSTGRES_PASSWORD: ${SL_POSTGRES_PASSWORD:-dbuser123}
      POSTGRES_DB: ${SL_POSTGRES_DB:-starlake}
      AIRFLOW_DB: ${AIRFLOW_DB:-airflow}
      DAGSTER_DB: ${DAGSTER_DB:-dagster}
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "${SL_POSTGRES_USER:-dbuser}", "-d", "${SL_POSTGRES_DB:-starlake}"]
      interval: "1s"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./conf/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts/airflow/init-database.sh:/docker-entrypoint-initdb.d/init-airflow-database.sh
      - ./scripts/dagster/init-database.sh:/docker-entrypoint-initdb.d/init-dagster-database.sh

  starlake-dagster:
    image: starlakeai/starlake-dagster:latest
    build:
      context: .  # Assuming Dockerfile_dagster is in the current directory
      dockerfile: Dockerfile_dagster
    container_name: starlake-dagster
    restart: on-failure
    depends_on:
      starlake-db:
        condition: service_healthy
    environment:
      DAGSTER_PG_USERNAME: ${SL_POSTGRES_USER:-dbuser}
      DAGSTER_PG_PASSWORD: ${SL_POSTGRES_PASSWORD:-dbuser123}
      DAGSTER_PG_HOST: starlake-db
      DAGSTER_PG_DB: ${DAGSTER_DB:-dagster}
      SL_HOME: /app/starlake
    entrypoint: >
      /bin/bash -c "
      sleep 10 &&
      pip install --no-cache-dir starlake-dagster docker --upgrade --force-reinstall &&
      python3 dagster_code_locations.py &&
      service cron --full-restart &
      exec dagster-webserver -h 0.0.0.0 -p 3000 --path-prefix /dagster"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket to run Docker commands from the container
      - ${PROJECTS_DATA_PATH:-./projects}:/projects
      - ${PROJECTS_DATA_PATH:-./projects}/dags:/opt/dagster/app/dags
      - ${DAGSTER_LOGS:-./dagster/logs}:/opt/dagster/app/logs
      - ${DAGSTER_STORAGE:-./dagster/storage}:/opt/dagster/home/storage
    ports:
      - ${SL_DAGSTER_PORT:-3000}:3000  # Dagster Webserver port

  starlake-ui:
    image: starlakeai/starlake-${SL_MAJOR_VERSION:-1.5}-ui:${SL_IMAGE_VERSION:-1.5}
    pull_policy: always
    container_name: starlake-ui
    restart: on-failure
    depends_on:
      starlake-db:
        condition: service_healthy
      starlake-dagster:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-s", "-I", "http://starlake-ui:9000/api/v1/health" ]
      interval: "5s"
      retries: 60
    ports:
      - 9000  # starlake-ui default port
    environment:
      - SL_HOME=/app/starlake
      - SL_FS=file://
      - SL_ENV=
      - SL_ROOT=
      - SL_USE_LOCAL_FILE_SYSTEM=false
      - SL_API_GIT_COMMAND_ROOT=/git
      - SL_API_SECURE=false
      - SL_API_SESSION_AS_HEADER=true
      - SL_API_HTTP_FRONT_URL=${SL_API_HTTP_FRONT_URL:-http://starlake-ui}
      - SL_API_HTTP_INTERFACE=0.0.0.0
      - SL_API_HTTP_PORT=9000
      - SL_LOG_LEVEL=${SL_LOG_LEVEL:-info}
      - SL_API_JDBC_DRIVER=org.postgresql.Driver
      - SL_API_JDBC_USER=${SL_POSTGRES_USER:-dbuser}
      - SL_API_JDBC_PASSWORD=${SL_POSTGRES_PASSWORD:-dbuser123}
      - SL_API_JDBC_URL=jdbc:postgresql://starlake-db:5432/${SL_POSTGRES_DB:-starlake}?user=${SL_POSTGRES_USER:-dbuser}&password=${SL_POSTGRES_PASSWORD:-dbuser123} # JDBC URL to connect to the database
      - SL_API_DOMAIN=${SL_API_DOMAIN:-localhost}
      - SL_API_PROJECT_ROOT=/projects
      - SL_API_ORCHESTRATOR_PRIVATE_URL=http://starlake-dagster:3000/dagster/
      - ENVIRONMENT=local # local environment
      - FILESTORE_MNT_DIR=/projects  # Environment variable to specify the mount path inside starlake-ui container
      - EXTERNAL_PROJECTS_MNT_DIR=/external_projects
      - POSTGRES_HOST=starlake-db
      - POSTGRES_DB=${SL_POSTGRES_DB:-starlake}
      - POSTGRES_USER=${SL_POSTGRES_USER:-dbuser}
      - POSTGRES_PASSWORD=${SL_POSTGRES_PASSWORD:-dbuser123}
      - SL_UI_DEMO=${SL_UI_DEMO:-false}
      - SL_API_MAIL_HOST=${SL_API_MAIL_HOST:-smtp.sendgrid.net}
      - SL_API_MAIL_PORT=${SL_API_MAIL_PORT:-587}
      - SL_API_MAIL_USER=${SL_API_MAIL_USER:-apikey}
      - SL_API_MAIL_PASSWORD=${SL_API_MAIL_PASSWORD:-}
      - SL_API_MAIL_FROM=${SL_API_MAIL_FROM:-contact@starlake.ai}
      - SL_API_MAX_USER_SPACE_MB=${SL_API_MAX_USER_SPACE_MB:-0}
      - SL_API_FILE_UPLOAD_MAX_CONTENT_LENGTH=${SL_API_FILE_UPLOAD_MAX_CONTENT_LENGTH:-1073741824} # 1 GB
      - _JAVA_OPTIONS=-XX:UseSVE=0
      - SL_API_UI_FOLDER=/app/ui
      - LOAD_DAG_REF=dagster_load_shell
      - TRANSFORM_DAG_REF=dagster_transform_shell
    entrypoint: >
      /bin/bash -c "
      sleep 10 &&
      python3 -m pip install --break-system-packages --no-cache-dir starlake-dagster docker --upgrade &&
      /usr/bin/tini -- /app/run-api.sh"
    volumes:
      - ./scripts/starlake:/usr/local/bin/starlake:ro
      - ${PROJECTS_DATA_PATH:-./projects}:/projects
      - ${EXTERNAL_PROJECTS_DATA_PATH:-./external_projects}:/external_projects

  starlake-projects:
    image: starlakeai/starlake-projects:latest
    build:
      context: .  # Assuming Dockerfile_projects is in the current directory
      dockerfile: Dockerfile_projects
    container_name: starlake-projects
    restart: on-failure
    depends_on:
      starlake-db:
        condition: service_healthy
      starlake-ui:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${SL_POSTGRES_USER:-dbuser}
      POSTGRES_PASSWORD: ${SL_POSTGRES_PASSWORD:-dbuser123}
      POSTGRES_DB: ${SL_POSTGRES_DB:-starlake}
      POSTGRES_HOST: starlake-db
    volumes:
      - ${PROJECTS_DATA_PATH:-./projects}:/projects

  starlake-proxy:
      image: starlakeai/starlake-proxy:${SL_IMAGE_VERSION:-0.1}
      pull_policy: always
      container_name: starlake-proxy
      restart: on-failure
      depends_on:
        starlake-db:
          condition: service_healthy
        starlake-dagster:
          condition: service_started
        starlake-ui:
          condition: service_healthy
      healthcheck:
        test: [ "CMD", "curl", "-s", "-I", "http://starlake-proxy:80/api/v1/health" ]
        interval: "5s"
        retries: 60
      ports:
        - ${SL_PORT:-80}:80  # starlake-proxy default port
      environment:
        - NODE_ENV=docker
        - SL_PORT=${SL_PORT:-80}

  starlake-agent:
    image: starlakeai/starlake-1.5-ask:0.1
    pull_policy: always
    container_name: starlake-agent
    restart: on-failure
    depends_on:
      starlake-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-s", "http://starlake-agent:8000/ask/health" ]
      interval: "5s"
      retries: 60
    ports:
      - ${SL_AI_PORT:-8000}:8000  # starlake-agent default port
    environment:
      - SL_ASK_APPLICATION_KEY=Starlake7157
      - SL_ASK_STARLAKE_JSON_FOLDER=/app/starlake_ask/resources
      - SL_ASK_PG_USER=${SL_POSTGRES_USER:-dbuser}
      - SL_ASK_PG_PASSWORD=${SL_POSTGRES_PASSWORD:-dbuser123}
      - SL_ASK_PG_DB=${SL_POSTGRES_DB:-starlake}
      - SL_ASK_PG_SERVER=starlake-db
      - SL_ASK_PG_PORT=5432
      - SL_ASK_API_SERVER_URL=http://starlake-proxy:80
      - SL_ASK_HOST=0.0.0.0
      - SL_ASK_DB_TYPE=postgres
      - SL_ASK_API_DOCS_USER=starlake
      - SL_ASK_API_DOCS_PASSWORD=s3cret.Paw

volumes:
  pgdata:
