version: '3.8'

services:
  minio:
    image: "quay.io/minio/minio:latest"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ "server", "--console-address", ":9001", "/data" ]
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    networks:
      - hive-net

  createbuckets:
    image: quay.io/minio/mc:RELEASE.2025-03-12T17-29-24Z
    depends_on:
      - minio
    restart: on-failure
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      S3_ENDPOINT: http://minio:9000
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set dockerminio \$$S3_ENDPOINT \$$MINIO_ACCESS_KEY \$$MINIO_SECRET_KEY;
      /usr/bin/mc mb --ignore-existing dockerminio/warehouse;
      exit 0;
      "
    networks:
      - hive-net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hive-net

  hive-metastore:
    build:
      context: ./hive
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - minio
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_PORT: 5432
      S3_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9083:9083"
    networks:
      - hive-net

  trino:
    build:
      context: ./trino
      dockerfile: Dockerfile
    depends_on:
      - hive-metastore
      - minio
    environment:
      HIVE_METASTORE_URI: thrift://hive-metastore:9083
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      S3_ENDPOINT: http://minio:9000
      AWS_REGION: us-east-1
    ports:
      - "8080:8080"
    networks:
      - hive-net

volumes:
  postgres-data:

networks:
  hive-net:
    driver: bridge
