services:
  minio:
    image: "quay.io/minio/minio:latest"
    ports:
      - "127.0.0.1:9900:9000"
      - "127.0.0.1:9001:9001"
    command: [ "server", "--console-address", ":9001", "/data" ]
    volumes:
      - '/Users/hayssams/git/public/hive3-metastore/minio/data:/data'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

  createbuckets:
    image: quay.io/minio/mc:RELEASE.2025-03-12T17-29-24Z
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set dockerminio http://minio:9000 minio minio123;
      /usr/bin/mc mb dockerminio/warehouse;
      exit 0;
      "

